version: '3.8'

services:
  php:
    build: ./php
    container_name: symfony_php
    volumes:
      - ./app:/var/www/html
      - ./app/var:/var/www/html/var
      - ./php/uploads:/var/www/uploads
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://symfony:symfony@db:3306/symfony
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./app/public:/var/www/html/public:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  db:
    image: mysql:8.0
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5
    container_name: symfony_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: symfony
      PMA_PASSWORD: symfony
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data: